# Generated by Django 5.0.2 on 2025-10-29 05:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MushroomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload a clear image of the mushroom (JPG, JPEG, or PNG)', upload_to='mushroom_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='mushroom image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='upload date')),
                ('is_edible', models.BooleanField(null=True, verbose_name='is edible')),
                ('edibility_confidence', models.FloatField(null=True, verbose_name='edibility confidence')),
                ('species', models.CharField(blank=True, max_length=100, verbose_name='species')),
                ('species_confidence', models.FloatField(null=True, verbose_name='species confidence')),
                ('lifespan', models.TextField(blank=True, verbose_name='lifespan')),
                ('preservation', models.TextField(blank=True, verbose_name='preservation')),
            ],
            options={
                'verbose_name': 'mushroom image',
                'verbose_name_plural': 'mushroom images',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='UnknownMushroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='unknown_mushrooms/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
