# Generated by Django 5.0.2 on 2025-11-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unknownmushroom',
            name='pin_color',
            field=models.CharField(default='#0d6efd', max_length=20),
        ),
        migrations.AddField(
            model_name='unknownmushroom',
            name='status',
            field=models.CharField(choices=[('mapped', 'Mapped (Default)'), ('edible', 'Edible'), ('poisonous', 'Poisonous'), ('unknown', 'Unknown')], default='mapped', max_length=20),
        ),
    ]
