# Generated by Django 5.0.2 on 2025-11-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_unknownmushroom_pin_color_unknownmushroom_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='unknownmushroom',
            name='description',
            field=models.TextField(blank=True, help_text='Additional description or notes'),
        ),
        migrations.AlterField(
            model_name='unknownmushroom',
            name='name',
            field=models.CharField(help_text='Species name or common name', max_length=150),
        ),
    ]
