# Generated by Django 5.0.2 on 2025-11-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_unknownmushroom_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unknownmushroom',
            name='is_pending',
            field=models.BooleanField(default=True, help_text='Pending reports stay off the public map until approved'),
        ),
        migrations.AlterField(
            model_name='unknownmushroom',
            name='status',
            field=models.CharField(choices=[('mapped', 'Mapped'), ('edible', 'Edible'), ('poisonous', 'Poisonous'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
