# Generated by Django 5.0.2 on 2025-11-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_unknownmushroom_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='unknownmushroom',
            name='origin',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unknownmushroom',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
